In [2]:
import numpy as np

In [3]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [4]:
def sugmoid_derivative(x):
    return x*(1-x)

In [5]:
training_input=np.array([[1,0,0],[0,1,1],[1,0,1],[0,1,0]])
training_input

array([[1, 0, 0],
       [0, 1, 1],
       [1, 0, 1],
       [0, 1, 0]])

In [6]:
training_output=np.array([[1,0,1,0]])
training_output

array([[1, 0, 1, 0]])

In [7]:
# maja nhi aaya isliye

training_output=np.array([[1,0,1,0]]).T
training_output

array([[1],
       [0],
       [1],
       [0]])

In [8]:
weights=np.array([[0],[0],[0]],dtype='float64')
weights


array([[0.],
       [0.],
       [0.]])

In [9]:
# Training of neural network

for i in range(100000):
    input_layer=training_input
    outputs=sigmoid(np.dot(input_layer,weights))
    error=training_output-outputs
    adujustment=error*sugmoid_derivative(outputs)
    weights=weights+np.dot(input_layer.T,adujustment)
outputs

array([[0.99841383],
       [0.00158617],
       [0.99841383],
       [0.00158617]])