In [ ]:
print("hello Anurag")

In [1]:
print("hello Anurag")


hello Anurag


In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [7]:
import numpy as np
a=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(a)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [8]:
# ndim is used to find dimention of an array



In [9]:
a=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(a.ndim)

2


In [10]:
# dtype is used to find datatype of numpy values

In [11]:
print(a.dtype)

int32


In [12]:
# itemsize :- it is used to find size fo element in numpy array

print(a.itemsize)

4


In [13]:
# shape is used to find shape of numpy array

print(a.shape)

(2, 5)


In [14]:
# size is used to find size of numpy array

print(a.size)

10


In [15]:
# reshape() :- function is used to change the shape of numpy array

a=a.reshape(5,2)
print(a) 

[[1 2]
 [3 4]
 [5 2]
 [3 4]
 [5 6]]


In [16]:
#max(),min(),sum()

print(a.max())
print(a.min())
print(a.sum())

6
1
35


In [4]:
import numpy as np
arr=np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [5]:
print(arr.dtype)

float64
